### ISSUE TITLE
Go to date

### ISSUE THREAD

**Issue by pillage** [twinssbc/AngularJS-ResponsiveCalendar#14]
I'd like to add a datepicker and be able to go to a specified date. Any idea how I can implement this?
Thanks.

**Comment by twinssbc** [comment]
@pillage sorry for the late response, you can refer to the today function in the demo.
Basically in the view, you assign a variable to the ng-model, for example, currentDate,
then in your datepicker select function, you can assign the selected date to currentDate.

**Comment by pillage** [comment]
Got it working thanks.
