### ISSUE TITLE
Change week start date

### ISSUE THREAD

**Issue by pillage** [twinssbc/AngularJS-ResponsiveCalendar#17]
Is it possible to change the starting day in 'Week' view from Sunday to Monday?

Thanks.

**Comment by twinssbc** [comment]
@pillage I just did some quick test. I found the below two lines in the weekview code and added one day to both the firstDayOfWeek and endTime. It appears the week view starts from Monday. Feel free to test further to see if everything works as expected.

```
                        firstDayOfWeek = new Date(year, month, date - day),
                        endTime = new Date(year, month, date - day + 7);
```

**Comment by pillage** [comment]
@twinssbc Looks good. Thanks.
