### ISSUE TITLE
Times in weekview not showing right

### ISSUE THREAD

**Issue by Ganganation** [twinssbc/AngularJS-ResponsiveCalendar#19]
Hi,

I am currently using this module to create my own calendar variant. While doing that I discovered a little bug. The times in the weekview are not showing right. Somehow it keep incrementing the time.getHours(). And sinds I am using that I had to fix it.

This is what I did:

old code (line 528 calendar.js):
<code>
function createDateObjects(startTime) {
                var times = [],
                    row,
                    time = new Date(startTime.getTime());

                for (var hour = 0; hour < 24; hour++) {
                    row = [];
                    for (var day = 0; day < 7; day++) {
                        time.setHours(time.getHours() + hour);
                        time.setDate(time.getDate() + day);
                        row.push({
                            time: new Date(time.getTime())
                        });

                        console.log(day, time.getDate());
                    }
                    times.push(row);
                }

                return times;
            }
</code>

New code:
<code>
function createDateObjects(startTime) {
                var times = [],
                    row,
                    time = new Date(startTime.getTime());

                var timeHours = time.getHours();
                var timeDay = time.getDate();

                for (var hour = 0; hour < 24; hour++) {
                    row = [];
                    for (var day = 0; day < 7; day++) {
                        time.setHours(timeHours + hour);
                        time.setDate(timeDay + day);
                        row.push({
                            time: new Date(time.getTime())
                        });

                        console.log(day, time.getDate());
                    }
                    times.push(row);
                }

                return times;
            }
</code>

I hope this helps!

**Comment by twinssbc** [comment]
@Ganganation Thanks for reporting!
The fix has been committed. 
https://github.com/twinssbc/AngularJS-ResponsiveCalendar/commit/51ab141030a764ca11bee3e724a5297fb94f5a01

**Comment by edmondchui** [comment]
Hi @twinssbc, could you please increment the (patch) version number in bower.json w.r.t. this change? Thanks.

**Comment by twinssbc** [comment]
@edmondchui I have updated the patch version in bower

**Comment by edmondchui** [comment]
Thanks @twinssbc !
