### ISSUE TITLE
Replace anonymous function with closure

### ISSUE THREAD

**Issue by edmondchui** [twinssbc/AngularJS-ResponsiveCalendar#20]
In the code https://github.com/twinssbc/AngularJS-ResponsiveCalendar/blob/master/src/rcalendar/calendar.js#L196-L201:

```js
angular.forEach(cells[index].events, function (e) {
  if (!e.overlapNumber) {
    e.overlapNumber = overlapNumber;
    eventQueue.push(e);
  }
});
```
Is it possible to replace the anonymous function in the loop with closure? jshint warns that Don't make functions within a loop.

It seems that with angular.forEach we don't get the looping variable. We might have to use for loop instead to get the looping variable to generate closure.

**Comment by twinssbc** [comment]
@edmondchui I replaced the forEach with the for loop.

**Comment by twinssbc** [comment]
@edmondchui I replaced the forEach with the for loop.

**Comment by edmondchui** [comment]
Thanks @twinssbc. jshint does not complaint the loop issue anymore!

One minor thing is that you've added ```'use strict';``` in each directive declaration. jshint says it's not necessary, even though I have ```"strict: true;``` specified in my .jshintrc file.

**Comment by twinssbc** [comment]
@edmondchui my jshint prompts Missing "use strict" statement. That's why I added them.
