### ISSUE TITLE
Automatically Switch to Day View on Small Screen Width

### ISSUE THREAD

**Issue by edmondchui** [twinssbc/AngularJS-ResponsiveCalendar#22]
What is the best way to achieve that?

**Comment by twinssbc** [comment]
@edmondchui you can try https://github.com/AnalogJ/matchmedia-ng or https://github.com/jacopotarantino/angular-match-media
set the calendar mode in the on() method

**Comment by edmondchui** [comment]
angular-match-media works awesome! Thanks!
