### ISSUE TITLE
Update eventSource without refresh page

### ISSUE THREAD

**Issue by almaweb** [twinssbc/AngularJS-ResponsiveCalendar#35]
I create an delete event function, all is ok and the event is delete from backend but the calendar didn't refresh. to see the change i must refresh the page....how can i archieve this without refreshing page...
Merci

**Comment by twinssbc** [comment]
@AlexSwensen the controller is watching the eventSource array, do you modify this array after you made the change at the backend?
Each time your backend update is successful, you have to call something like 
```
$scope.eventSource = fetchDataFromBackend();
```
Or you can directly modify the element of the existing eventSource array then manually fire the event.
```
$scope.$broadcast('eventSourceChanged',$scope.eventSource);
```

**Comment by almaweb** [comment]
Exuse me but i am no t an angular expert 
    $scope.loadEvents = function ()  {
            agendaService.getEvents()
              .then(function (result) {
   
                $scope.myevents = result.data;
                var events = [];
                for (var i = $scope.myevents.length - 1; i >= 0; i--) {
                    var date = new Date();
                    var prop = $scope.myevents[i];            
                    var startDate, startTime, eventStartDate;
                    startDate = prop.date_event_debut; 
                    startTime = '09:00:00';                                    
                    eventStartDate = new Date(startDate+'T'+startTime);            
                    var endDate, endTime, eventEndDate;
                    endDate = prop.date_event_debut;  
                    endTime = '11:00:00';                           
                    eventEndDate = 'new Date(endDate+'T'+endTime)';
                    events.push({
                        id: prop.id,                        
                        title: 'Event - ' + i,
                        startTime: eventStartDate,
                        endTime: eventEndDate,
                        allDay: false
                    });
                }
                $scope.eventSource = events;
            });

        };
 where to put ; $scope.$broadcast('eventSourceChanged',$scope.eventSource);

**Comment by twinssbc** [comment]
@almaweb actually your code looks correct, since you assign the entire array to eventSource, you don't need to broadcast the event.
Could you also provide your html part?

**Comment by almaweb** [comment]
this is my month view, i only add a button to delete event with his action and for css i use materializecss
<div>
    <table class="table table-bordered monthview-datetable monthview-datetable">
        <thead>
        <tr>
            <th ng-show="showWeeks" class="calendar-week-column text-center">#</th>
            <th ng-repeat="label in labels track by $index" class="text-center">
                <small>{{label}}</small>
            </th>
        </tr>
        </thead>
        <tbody>
        <tr ng-repeat="row in rows track by $index">
            <td ng-show="showWeeks" class="calendar-week-column text-center">
                <small><em>{{ weekNumbers[$index] }}</em></small>
            </td>
            <td ng-repeat="dt in row track by dt.date" class="monthview-dateCell" ng-click="select(dt.date)"
                ng-class="{'text-center':true, 'monthview-current': dt.current&&!dt.selected&&!dt.hasEvent,'monthview-secondary-with-event': dt.secondary&&dt.hasEvent, 'monthview-primary-with-event':!dt.secondary&&dt.hasEvent&&!dt.selected, 'monthview-selected': dt.selected}">
                <div ng-class="{'text-muted':dt.secondary}">
                    {{dt.label}}
                </div>
            </td>
        </tr>
        </tbody>
    </table>
    <div ng-if="showEventDetail" class="event-detail-container">
        <div class="scrollable" style="height: 200px">
            <table class="table table-bordered table-striped table-fixed">
                <tr ng-repeat="event in selectedDate.events" ng-if="selectedDate.events">
                    <td ng-if="!event.allDay" class="monthview-eventdetail-timecolumn">{{event.startTime|date: 'HH:mm'}}
                        -
                        {{event.endTime|date: 'HH:mm'}}
                    </td>
                    <td ng-if="event.allDay" class="monthview-eventdetail-timecolumn">All day</td>
                    <td class="event-detail" ng-click="eventSelected({event:event})">{{event.title}}</td>
                    <td class="event-detail right" ng-click="deleteSelected({event:event})">delete event</td>                    
                </tr>
                <tr ng-if="!selectedDate.events"><td class="no-event-label">No Events</td></tr>
            </table>
        </div>
    </div>
</div>

**Comment by almaweb** [comment]
I only add a button to delete event, all the rest is the same to your template...

**Comment by AlexSwensen** [comment]
@twinssbc Im not sure i understand the question... The changes i made to this project were only related to controlling part of the calendar from an external component.

**Comment by almaweb** [comment]
yes....
Could you update your package with some button to delete event.....it will be very cool

**Comment by twinssbc** [comment]
@almaweb I will try to add more samples in the demo during the weekend.
Could you send out the main html page which contains the <calendar> tag. I suspect you didn't assign the eventSource to a correct scope.

**Comment by almaweb** [comment]
Yes , you r right ...it was a problem with eventSource..Sorry
I will wait for your samples to restruct my hole project in a correct way..
