### ISSUE TITLE
Integrate with ionic app ?

### ISSUE THREAD

**Issue by hatim-haffane** [twinssbc/AngularJS-ResponsiveCalendar#36]
hello i try to integrate this with an ionic app , the calendar shows well but the event not showing , here is my code : 

Controller : 

    app.controller('testCtrl', function($scope, $stateParams,ReservationService,$ionicContentBanner) {
	$scope.events = [];//createRandomEvents();
	// Rest api Call 
	ReservationService.getById(33,setbookings);

	function setbookings(data){
    	$scope.groups = data.data; 
    	_.each($scope.groups, function(group) {
  			add_event(group);
		})
    	console.log('bookings '+JSON.stringify(_.groupBy($scope.groups, "bookdate")));
    	
  	}

  	function add_event(group){
  		$scope.events.push({
            title: group.pick_point +'<i class="icon ion-ios-arrow-thin-right" style="font-size:16px;vertical-align: middle;">'+ group.drop_point,
            startTime: new Date(group.pick_datetime),
            endTime: '',
            allDay: false
            });
  	}});

the view : 
     ion-content ng-controller="testCtrl" ng-init="loadEvents()">
        calendar calendar-mode="month" event-source="events" >
       /ion-content>

any help please

**Comment by twinssbc** [comment]
@hatim-haffane are you using the latest version of this calendar control? I recently fixed a bug that the controller only watches the "eventSource" expression.
So you can try event-source="eventSource" or use the latest version.
BTW, i also have a customised version for ionic, it includes some optimisation to avoid the performance issue, I will find some time to upload it.

If you find the navigation between pages are slow, it's worth to try disabling the animation.
        $animate.enabled(false);

**Comment by hatim-haffane** [comment]
thanks i will try the last version . and i will be thankful if you can upload the ionic version of this wonderful plugin

**Comment by hatim-haffane** [comment]
i tried  the new version but i still cant see the event , and the css is missed up, can you please send me the ionic version ?

**Comment by twinssbc** [comment]
@hatim-haffane I will clean up the ionic version and send out during the weekend.

**Comment by twinssbc** [comment]
@hatim-haffane Here is the Ionic version.
https://github.com/twinssbc/Ionic-Calendar
Feel free to test it and report any bug. Thanks.
