### ISSUE TITLE
Wrong week number showing for January

### ISSUE THREAD

**Issue by pucchur** [twinssbc/AngularJS-ResponsiveCalendar#38]
In month view of January it shows wrong week number 

![wekknumber](https://cloud.githubusercontent.com/assets/3825401/12177033/27ecabaa-b562-11e5-8007-0234c84fbb8b.jpg)

**Comment by twinssbc** [comment]
@pucchur Thanks for reporting this bug, I have submitted the fix in version 0.1.10. Could you have a check? Thanks.

**Comment by pucchur** [comment]
Brilliant work ... shows correct week numbers
