### ISSUE TITLE
Hide Next  Navigation

### ISSUE THREAD

**Issue by nishadotcom** [twinssbc/AngularJS-ResponsiveCalendar#39]
Hai @twinssbc 

How to hide the next navigation icon for disabling future date????

Best
nishadotcom

**Comment by twinssbc** [comment]
@nishadotcom You can navigate to template/rcalendar/calendar.html and remove below lines to remove the next icon button.

```
        <div class="nav-right col-xs-2">
            <button type="button" class="btn btn-default btn-sm" ng-click="move(1)"><i
                    class="glyphicon glyphicon-chevron-right"></i></button>
        </div>
```

**Comment by nishadotcom** [comment]
Sorry, I need the next icon because if I click on Previous I need to come back.

My question is 
      ** How to hide the Next icon to for future dates????**

I mean, The current month is **January 2015**. When I am in January, I should not have the Next icon to see the **Feb 2015**, **Mar 2015 ....**

Best
nishadotcom

**Comment by twinssbc** [comment]
@nishadotcom I guess I understand your question now. What you can do is to use ngHide or ngShow, they support expression. So in the expression you can call a function which will compare the current date with the current display month, and if it's in the current month, then return false.

**Comment by nishadotcom** [comment]
Thanks @twinssbc .

I have done by comparing title and my date.
