### ISSUE TITLE
The event is displayed wrongly in calendar

### ISSUE THREAD

**Issue by jsmasterathul** [twinssbc/AngularJS-ResponsiveCalendar#44]
This is my event source

> $scope.eventSource = [
>                             {
>                                 title: 'All Day - 1',
>                                 startTime: new Date(2016,2,1),
>                                 endTime: new Date(2016,2,2),
>                                 allDay: true
>                             },
>                             {
>                                 title: 'All Day - 2' ,
>                                 startTime: new Date(2016,2,1),
>                                 endTime: new Date(2016,2,2),
>                                 allDay: true 
>                             },
>                             {
>                                 title: 'All Day - 3' ,
>                                 startTime: new Date(2016,2,2),
>                                 endTime: new Date(2016,2,2),
>                                 allDay: true 
>                             }];

The  events are displayed one day prior when it comes to calendar, do we need to specify time zone also?

**Comment by twinssbc** [comment]
@jsmasterathul If you want to use allDay event, you have to set the time part to 0:00AM. There's explanation in the README. Thanks.
