### ISSUE TITLE
All Day event not showing in Next and Previous months

### ISSUE THREAD

**Issue by captainmorgan0** [twinssbc/AngularJS-ResponsiveCalendar#52]
I have created an event in the previous month, current month and next month. When I load the calendar, in the current month view, I can see one dark blue day and 2 light blue days (for the events in the previous an next month). When I go to the previous or next month the all day event is not displayed (the day is not dark blue, it remains white). And when I click on the day it displays "No Events" You can see this event in week and day views.

**Comment by twinssbc** [comment]
@captainmorgan0 Could you give me a specific sample on which date you put the event so that I can try to reproduce it?

**Comment by captainmorgan0** [comment]
Add aan all day event for May 5th

**Comment by twinssbc** [comment]
@captainmorgan0 I can't reproduce it. See the below screenshots and code snippets.

```
        var s = new Date(Date.UTC(2016, 3, 5));
        var e = new Date(Date.UTC(2016, 3, 6));
        events.push({
            title: 'All Day - test',
            startTime: s,
            endTime: e,
            allDay: true
        });

        var s = new Date(Date.UTC(2016, 4, 5));
        var e = new Date(Date.UTC(2016, 4, 6));
        events.push({
            title: 'All Day - test',
            startTime: s,
            endTime: e,
            allDay: true
        });
        var s = new Date(Date.UTC(2016, 5, 5));
        var e = new Date(Date.UTC(2016, 5, 6));
        events.push({
            title: 'All Day - test',
            startTime: s,
            endTime: e,
            allDay: true
        });
```

![screen shot 2016-04-20 at 8 21 03 am](https://cloud.githubusercontent.com/assets/3329841/14659746/20cde4cc-06d1-11e6-87b1-1d66637b9bd4.png)
![screen shot 2016-04-20 at 8 22 17 am](https://cloud.githubusercontent.com/assets/3329841/14659749/291825a2-06d1-11e6-81be-4f11ad68b1ea.png)
![screen shot 2016-04-20 at 8 22 27 am](https://cloud.githubusercontent.com/assets/3329841/14659757/35e619ce-06d1-11e6-95fb-2410e9ec2535.png)

**Comment by captainmorgan0** [comment]
I now see what I was doing wrong. I had the start and end dates the same.
