### ISSUE TITLE
Switch to day view from month view by clicking on a date 

### ISSUE THREAD

**Issue by Django999** [twinssbc/AngularJS-ResponsiveCalendar#55]
Is it possible to switch to day view from month view  by clicking on a day with events ?.On click of a date in month view I need to switch to day view and show its events there.I am new to angular ,and  unable to figure out how to do it.

**Comment by twinssbc** [comment]
@Django999 It's possible. In your time selected callback, you just need to change the calendar mode.

```
$scope.onTimeSelected = function (event) {
    if($scope.mode === 'month') {
            $scope.mode = 'day';
        }
};
```

**Comment by Django999** [comment]
@twinssbc Ok Thanks for the solution
