### ISSUE TITLE
Callback on "Prev" and "Next" click

### ISSUE THREAD

**Issue by isteven** [twinssbc/AngularJS-ResponsiveCalendar#59]
Hi @twinssbc , 

Thanks for the directive, it's really helpful. 

I need to create a callback when the next / prev button is clicked. Something similar with this: #40.

As suggested there, I tried using the "range-changed" attribute, but I'm still unable to get my callback function triggered.

My HTML:
```htm
<calendar
    calendar-mode="month"    
    range-changed="rangeChanged(startTime, endTime)"
 ></calendar>
```

My Javascript:
```js
$scope.rangeChanged = function (startTime, endTime) {
    console.log(startTime, endTime); // should print something, but empty
}
```

Any help would be appreciated. Thanks.

**Comment by isteven** [comment]
Sorry, just ignore this question, I manage to do it already. Will open a new issue.

**Comment by iamntg** [comment]
@isteven Hi, I am facing the same problem. how did you managed to get this done?

**Comment by twinssbc** [comment]
@iamntg What's your issue? The rangeChanged callback is not triggered?
This callback is only triggered when the queryMode is set to 'remote', did you set it?

**Comment by iamntg** [comment]
@twinssbc Hey, it was fixed, Thank you. The queryMode need to be set as variable from the controller. I was trying to set it directly from the html.
