### ISSUE TITLE
All Day not working.

### ISSUE THREAD

**Issue by captainmorgan0** [twinssbc/AngularJS-ResponsiveCalendar#61]
I have the following example where there are 3 all day events, yet they are spanning multiple days
https://plnkr.co/edit/5BOY1ATjFFShsehzpilZ?p=preview

My computer's timezone is set to UTC+10:00 Canberra, Melbourne, Sydney.

Am I doing something wrong, or is there a bug? I am using Chrome for my browser

I did discover if I set my timezone to UTC 0, then the all day events appear correctly.

**Comment by twinssbc** [comment]
@captainmorgan0 
Yes. For all day events, the start time and event time has to be in UTC format. I've mentioned it in README.

**Comment by captainmorgan0** [comment]
If you have a look at my example i created, you will see that i am using UTC format.

`var startTime = new Date(Date.UTC(2016, 09, 04));
        var endTime = new Date(Date.UTC(2016, 09, 05));
        events.push({
                    title: 'Event - 1',
                    startTime: startTime,
                    endTime: endTime,
                    allDay: true
                });
        `

**Comment by captainmorgan0** [comment]
I believe there is an issue with daylight savings times, as last week we started daylight savings time. If I change my timezeone to UTC +10:00 Brisbane (which doesn't have daylight savings), the events appear correctly.

**Comment by twinssbc** [comment]
@captainmorgan0 
I think it's a bug.
I have fixed it in version 0.1.15.
Could you have a check? Thanks!

**Comment by captainmorgan0** [comment]
That works now. thanks
