### ISSUE TITLE
 ECONFLICT angular / bootstrap 

### ISSUE THREAD

**Issue by Ethenikset** [twinssbc/AngularJS-ResponsiveCalendar#62]
Hi, I have  "ECONFLICT Unable to find suitable version for angular" when i want to install.

here my CMD:
> $ bower install ng-responsive-calendar
> ...
> bower                                 ECONFLICT Unable to find suitable version for angular 

> {
>   "dependencies": {
>     "jquery": "~2.2.0",
>     "ng-lodash": "~0.3.0",
>     "angular": "~1.4.9",
>     "angular-bootstrap": "~1.1.1",
>     "seiyria-bootstrap-slider": "~6.0.8",
>     "angular-bootstrap-slider": "~0.1.24",
>     "angular-sanitize": "~1.4.9",
>     "angular-local-storage": "~0.2.3",
>     "angular-gridster": "~0.13.5",
>     "components-font-awesome": "~4.5.0",
>     "angular-daterangepicker-plus": "~0.1.17",
>     "ng-csv": "~0.3.6",
>     "isteven-angular-multiselect": "~4.0.0",
>     "checklist-model": "~0.9.0",
>     "angular-ui-utils": "~3.0.0",
>     "angular-socket-io": "~0.7.0",
>     "socket.io-client": "~1.4.4",
>     "angular-route": "~1.4.9",
>     "angular-resource": "~1.4.9",
>     "angular-google-maps": "2.3.2",
>     "angular-simple-logger": "~0.1.7",
>     "ng-file-upload": "^12.2.13",
>     "startbootstrap-sb-admin-2": "https://github.com/BlackrockDigital/startbootstrap-sb-admin-2.git#master",
>     "font-awesome": "^4.6.0",
>     "angular-dynamic-locale": "^0.1.32",
>     "angular-moment": "^1.0.1"
>   },
> }

that's my bower.json , I don't know what to do .
If someone have an issue i'll be thanksfull !

**Comment by twinssbc** [comment]
@Ethenikset When you run bower install ng-responsive-calenar command, is there any prompt let you to choose the Angular version? Because this calendar was written to be compatible with 1.2, and you have 1.4.9 in your bower.json.
Below is my console output:
I need to choose angular#~1.4.9 explicitly.
```
Bocongs-Mac-mini:testAngularCalendar twinssbc$ bower install ng-responsive-calendar
bower ng-responsive-calendar#*  cached https://github.com/twinssbc/AngularJS-ResponsiveCalendar.git#0.1.16
bower ng-responsive-calendar#*         validate 0.1.16 against https://github.com/twinssbc/AngularJS-ResponsiveCalendar.git#*
bower angular#~1.2                       cached https://github.com/angular/bower-angular.git#1.2.32
bower angular#~1.2                     validate 1.2.32 against https://github.com/angular/bower-angular.git#~1.2

Unable to find a suitable version for angular, please choose one:
    1) angular#~1.2 which resolved to 1.2.32 and is required by ng-responsive-calendar#0.1.16
    2) angular#~1.4.9 which resolved to 1.4.14 and is required by angular-responsive-calendar-client

Prefix the choice with ! to persist it to bower.json

? Answer: 2
bower ng-responsive-calendar#~0.1.16    install ng-responsive-calendar#0.1.16

ng-responsive-calendar#0.1.16 bower_components/ng-responsive-calendar
├── angular#1.4.14
└── bootstrap#3.0.3
Bocongs-Mac-mini:testAngularCalendar twinssbc$ 
```

**Comment by Ethenikset** [comment]
I have no choice to find a version of angular. He don't want to let me pick another version

**Comment by twinssbc** [comment]
@Ethenikset If you type **bower info angular**, what's the available version?

**Comment by Ethenikset** [comment]
1.0.3 to 1.6.1

> Available versions:
  - 1.6.1
  - 1.6.0
  - 1.5.11
  - 1.5.10
  - 1.5.9
  - 1.5.8
  - 1.5.7
  - 1.5.6
  - 1.5.5
  - 1.5.4
  - 1.5.3
  - 1.5.2
  - 1.5.1
  - 1.5.0
  - 1.4.14
  - 1.4.13
  - 1.4.12
  - 1.4.11
  - 1.4.10
  - 1.4.9
  - 1.4.8
  - 1.4.7
  - 1.4.6
  - 1.4.5
  - 1.4.4
  - 1.4.3
  - 1.4.2
  - 1.4.1
  - 1.4.0
  - 1.3.20
  - 1.3.19
  - 1.3.18
  - 1.3.17
  - 1.3.16
  - 1.3.15
  - 1.3.14
  - 1.3.13
  - 1.3.12
  - 1.3.11
  - 1.3.10
  - 1.3.9
  - 1.3.8
  - 1.3.7
  - 1.3.6
  - 1.3.5
  - 1.3.4
  - 1.3.3
  - 1.3.2
  - 1.3.1
  - 1.3.0
  - 1.2.32
  - 1.2.31
  - 1.2.30
  - 1.2.29
  - 1.2.28
  - 1.2.27
  - 1.2.26
  - 1.2.25
  - 1.2.24
  - 1.2.23
  - 1.2.22
  - 1.2.21
  - 1.2.20
  - 1.2.19
  - 1.2.18
  - 1.2.17
  - 1.2.16
  - 1.2.15
  - 1.2.14
  - 1.2.13
  - 1.2.12
  - 1.2.11
  - 1.2.10
  - 1.2.9
  - 1.2.8
  - 1.2.7
  - 1.2.6
  - 1.2.5
  - 1.2.4
  - 1.2.3
  - 1.2.2
  - 1.2.1
  - 1.2.0
  - 1.0.8
  - 1.0.7
  - 1.0.6
  - 1.0.5
  - 1.0.4
  - 1.0.3

**Comment by twinssbc** [comment]
I think as a workaround you can install ng-responsive-calendar in an empty folder and copy the install files to your project. I will do more investigation to understand why you get this error.

**Comment by Ethenikset** [comment]
ok problem fixed ! It's due to windows's rights . I have uninstall all dependencies and in a virtual machine I have clone my project, installed my dependencies, copy past my bower.json on windows and install again. That have worked. 

Thanks again for your help !
