### ISSUE TITLE
Layout on hours column is messy

### ISSUE THREAD

**Issue by leceal** [twinssbc/AngularJS-ResponsiveCalendar#64]
Hi, i'm having an issue where the event doesn't show properly in the hours column. For example, if my event is from 2:00 to 23:30, the collum gets filled up to 9 ish or 10 ish, doesn't fill the proper hour block. Any idea where can i watch this?

**Comment by twinssbc** [comment]
@leceal Could you print out your event object to see what's the startTime and endTime? Is it a standard date object? Is the event start hour displayed correct, only the end hour wrong?

**Comment by leceal** [comment]
Hey, thanks for you incredible fast answer. Yeah, it is a standar Date object, i'm attaching two pics where you can see two events:

Event One = 00:00 - 18:00
Event Two = 02:00 - 18:00

Both end at same time but start on different times, and you can see the layout for the start time is perfect, but the end time is messy hahaha.

![start event time](https://cloud.githubusercontent.com/assets/13887879/24200165/f5f34670-0eea-11e7-883c-c001b43c299e.jpg)
![end event time](https://cloud.githubusercontent.com/assets/13887879/24200166/f6052dae-0eea-11e7-8c79-ba3b2dedc8e0.JPG)

Thanks for your help

**Comment by twinssbc** [comment]
@leceal Which timezone are you in?

**Comment by leceal** [comment]
(UTC-03:00) Santiago.

**Comment by leceal** [comment]
Found the "error" is on the view (HTML/CSS side). The class "calendar-hour-column" is at 50px, which make the hours 10, 11, 12 to do a line break with the "A.M" or "P.M", which make the "height" of those rows thicker, which make the "event filler formula" (left: 100/displayEvent.overlapNumber*displayEvent.position+'%', width: 100/displayEvent.overlapNumber+'%', height: 37*(displayEvent.endIndex-displayEvent.startIndex)+'px') to fail filling correctly the event

**Comment by twinssbc** [comment]
@leceal OK. The 50px width is only for the default text. If you need to provide customized text, you need to override CSS to make the hour column wider.
