### ISSUE TITLE
How to give to onTimeSelected() event informations ?

### ISSUE THREAD

**Issue by SamTPang** [twinssbc/AngularJS-ResponsiveCalendar#67]
Hello,

I have on my calendar some events but when onEventSelected is fired, onTimeSelected too.
The required behavior is firing of onTimeSelected only when there is a click outside of an event.

I need to have either event informations in onTimeSelected method or the selectedTime in onEventSelected in order to set this behavior..

Any idea how to proceed ?

Best regards.

**Comment by twinssbc** [comment]
@SamTPang I have added events parameter in onTimeSelected callback. It has been released in version 0.1.17. Feel free to have a try.
