### ISSUE TITLE
Entries don't appear in iOS

### ISSUE THREAD

**Issue by scherhak** [twinssbc/AngularJS-ResponsiveCalendar#69]
Hi,

The calendar entries don't appear on iOS devices (in my case). Android works. Now someone about it?

Kind regards!

**Comment by twinssbc** [comment]
@scherhak Which Angular version are you using? What's the calendar entries are you referring to? Does the calendar itself display correctly? Only the events don't appear?

**Comment by scherhak** [comment]
@twinssbc Thanks for reply. I using AngularJS 1.6.4 and get the entries via $http.get. Basically everything works very well. See ...
Screen [iOS / Safari (also Chrome)](http://www.evernote.com/shard/s9/sh/24013e67-1366-4e46-9af1-e128d8c08d8d/93a9c863de388a095c86bedefc4c30d8)
Screen [Android / Chrome](http://www.evernote.com/shard/s9/sh/a1d1051c-afcb-4da8-bfa8-74637bb6113e/246dbcca5f97a8fd6de83c8694305516)
