### ISSUE TITLE
The time interval is not displayed correctly.

### ISSUE THREAD

**Issue by Komald** [twinssbc/AngularJS-ResponsiveCalendar#72]
The time slots having time in minutes is not getting displayed properly in week view and day view.

In the attached screen shot of week view, it's clear that the event start at 6.31 but on the calendar it's showing right from 6.00.
Similarly in day view screen shot the event starting at 1:48 (nearing to 2:00) is showing right from 1:00 and end time as 4:38 is stretched upto 4:59.
These are the screen shots from the demo page, but same thing is happening on my machine as well.

Please let me know the solution for this.

Cheers! 
![week-view](https://user-images.githubusercontent.com/6247575/33111026-b92b614e-cf71-11e7-8346-40a3529f5c33.png)
![day-view](https://user-images.githubusercontent.com/6247575/33111027-b9c0c860-cf71-11e7-96c6-0fff8bc6e387.png)

**Comment by twinssbc** [comment]
@Komald Are you saying the event should not occupy the whole cell, but part of the cell depending on the minute? Actually if you check other calendar controls, that is the default behavior. It's not reasonable to calculate the height of an event depending on the minutes. Let's say if you have an event starting from 1:00 to 1:01, the height of this event will be very small, you won't be able to select it.

**Comment by Komald** [comment]
Quite right for the small intervals you said, but for others if we can divide the hour in two parts and round up to nearing time it would be good. Similar to what's been happening in [ui-calendar](https://github.com/angular-ui/ui-calendar)

I found that it's setting from calendar-tpls.js but I did't get time to dig around much. Will try to find something over couple of days.

**Comment by twinssbc** [comment]
I've implemented this feature in my other calendar controls. I could port this feature into this control, but will take some time.

**Comment by Komald** [comment]
Cool!
Please let me know if you create some pull request for the same.

**Comment by twinssbc** [comment]
@Komald I have added 'step' option in the latest version. Feel free to give a try.

**Comment by Komald** [comment]
Awesome! That really did the job.
I have updated the version and it's working seamless.
Thanks vary much!
I will proceed and close this issue then.
