### ISSUE TITLE
Selected day (today) stays selected when moved to next/prev month

### ISSUE THREAD

**Issue by slishnevsky** [twinssbc/AngularJS-ResponsiveCalendar#75]
Selected day (today) stays selected when moved to next/prev month
Hi, when I click on arrows to navigate to next/prev month, selected day (which is today's date) is still displayed for another month. Say, today is 13-Apr. This days is selected on the calendar. But after clicking next, the calendar displays May month, with 13 selected.

**Comment by twinssbc** [comment]
@slishnevsky This is expected behavior. When you switch to next month, the selected date will be changed accordingly.

**Comment by slishnevsky** [comment]
Understood, thank you.
