### ISSUE TITLE
Migrate to Angular?

### ISSUE THREAD

**Issue by slishnevsky** [twinssbc/AngularJS-ResponsiveCalendar#80]
This is not an issue, just didnt know where to post the question....

So far this is the only simple and clean calendar app that I have found, that can display events and that can be easily customizable.

![image](https://user-images.githubusercontent.com/2932739/48662304-52111500-ea4e-11e8-8146-f70199b7ab3c.png)

Since AngularJS is a little outdated, can you convert it into Angular 2+ so that it can be used with an Angular app?

**Comment by twinssbc** [comment]
@slishnevsky Yes, I will convert it, but I'm quite busy right now, may have some time when the year end comes.

**Comment by twinssbc** [comment]
@slishnevsky I have created the Angular version of this calendar. Feel free to give a try.
https://github.com/twinssbc/Angular-Customizable-Calendar
